# Get nginx base image
FROM nginx

# Copy softy-pinko-front-end to Docker image
COPY ./softy-pinko-front-end /var/www/html/softy-pinko-front-end
COPY ./softy-pinko-front-end.conf /etc/nginx/conf.d/default.conf

