version: '3'

services:
  proxy:
    build:
      context: './proxy'
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task5
    ports:
      - '80:80'
    depends_on:
      - front-end
  back-end:
    build:
      context: './back-end'
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task5
    ports:
      - '5252:5252'
    depends_on:
      - front-end
  front-end:
    build:
      context: './front-end'
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task5
    ports:
      - '9000:9000'